project:
  type: website
  output-dir: docs

website:
  title: "Susan Canavan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: media.qmd
        text: Media
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual